### ISSUE TITLE
propnet should have a "debug" mode

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#113]
with added logging to the stdout to show what models are being evaluated at the moment

**Comment by computron** [comment]
you can also consider having a "timeout" function for a model so it gets skipped if it doesn't finish in a certain number of seconds

**Comment by mkhorton** [comment]
Good idea.

With regards to timeout, I propose we add a `ModelEvaluationTimeoutError` to [propnet.core.exceptions](https://github.com/materialsintelligence/propnet/blob/master/propnet/core/exceptions.py).

I've also been really enjoying https://www.sentry.io for automatic aggregation of errors. It might be a bit user-hostile to have it enabled by default, but for internal testing it might be a nice idea. Basically, wherever you normally raise an Exception, you call `sentryClient.captureException` and this will log the exception. You can set it up to automatically tag by git commit too.

**Comment by montoyjh** [comment]
We've added a considerable amount of logging to the graph evaluation procedure, along with a debug mode in the web app.  There's also an option to invoke the python debugger in model validation from the cli so I'm going to close this for now.
