### ISSUE TITLE
gruneisen parameter based on elastic modulus (long. + transverse sound velocities)

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#114]
see:

https://journals.aps.org/prb/pdf/10.1103/PhysRevB.94.125209

https://link.springer.com/content/pdf/10.1134%2FS1063784209090254.pdf

also not sure if Slack model of thermal conductivity is in there or not
![screen shot 2018-07-10 at 4 45 21 pm](https://user-images.githubusercontent.com/986759/42543438-bd04d652-8460-11e8-9f35-95db29a8009c.png)

**Comment by computron** [comment]
(see also: https://github.com/materialsintelligence/propnet/issues/40 regarding the Slack model)

**Comment by montoyjh** [comment]
Implemented in belomestnikh gruneisen.
