### ISSUE TITLE
New exception needed: ModelEvaluationTimeoutError

### ISSUE THREAD

**Issue by mkhorton** [materialsintelligence/propnet#142]
To inherit from TimeoutError.

Several models are going to be pathological in some instances in the builder, and we're going to keep running into mysterious build issues if we don't implement a time limit. Could implement a timeout keyword arg when initializing a Graph instance (default = 1s?)

To implement, perhaps use async to run the individual models at each graph evaluation step.

**Comment by clegaspi** [comment]
The timeout feature will be implemented in #200

**Comment by clegaspi** [comment]
Functionality implemented, although did not create custom error type.
