### ISSUE TITLE
Type errors causing NaN values to be returned

### ISSUE THREAD

**Issue by clegaspi** [materialsintelligence/propnet#158]
Noted that when running a graph evaluation on "mp-22851", several of the derived properties came back as "NaN". The nan values originate from evaluating the `homogeneous_elasticity_relations.py` model, specifically, `calc_G()` where "M" (P-wave modulus) is available. The value under the sqrt is negative. However, using the derived values of the Young's and P-wave modulus, I don't get this error when calculating by hand. So, my guess is that it happens when evaluating the error propagation values (although I have not confirmed that).

Possible solutions:

1. Set `numpy.seterr()` to raise an exception for this and other related errors. This will be caught by the existing exception handler.
2. Write code into `Model.evaluate()` to check for NaN values and raise an error ourselves. Benefits would be that we can provide more useful information to the user regarding the error. Perhaps giving the user the opportunity to check their values or their custom-built model.
3. Fix the specific homogeneous elasticity relations model to account for a possible invalid value (probably something to do in addition to 1 or 2 above).

Soliciting opinions, and...go!

**Comment by clegaspi** [comment]
Implemented a nan checker in #159 which rejects model evaluations that contain nans. However, upon further investigation as to why there were nans in the first place, it seems we have some typing issues.

Quantity is implemented using python types (int, float) and numpy arrays (numpy.ndarray). When propnet evaluates models which use Quantity objects with numpy arrays, the resultant (usually) scalar is a numpy float (usually numpy.float64) as opposed to a python float. The problem with numpy floats is that when you perform an operation on the numpy float that results in a complex number (ex. `np.float64(-1.)**(0.5)`, or `np.power(-1.,0.5)`) the result will be a np float with nan as the value. If the same operation is done with python floats (i.e. `float(-1.)**(0.5)`), it will output a complex.

I think that we should be storing scalars as python types to avoid typing problems like this one, especially because we have `PyModel` returning who knows what and we need the input to these models to be consistent.

So, I think we need to cast any scalar that outputs as a numpy type to the appropriate python type, unless there is a practical reason we need numpy types (which, I'm guessing, we don't have one at this time based on how this is implemented).

**Comment by clegaspi** [comment]
Talking with @dmrdjenovich about this a bit, an idea came up to split off Quantity into subclasses to hold different types of data. I know @mkhorton had talked about this in terms of having a non-numerical quantity class and a numerical one (then there would be less `if self.is_pint` or the like). Perhaps we could take this a bit further and have ScalarQuantity and ArrayQuantity or something like that (or IntQ, FloatQ, ComplexQ? Maybe not this far). That way we can control our data types a little bit better.

Drawbacks are that this could detract from simplicity in usability for end users trying to evaluate models. I'd have think more about how this would impact creating yaml files, which is the part we really want to be user-friendly.

Another thought, should we be including constraints in the models to check if quantities are real (in cases where it's necessary)?

**Comment by mkhorton** [comment]
I'm pro splitting them up into a pint-quantity + generic-quantity (or whatever you might want to name these).

However, I would take a hint from both NumPy and pint and keep all quantities with units in the same class rather than further splitting these up -- e.g. you can create an `np.array([1])` or `np.array([1,2,3])` or `np.array([[1,0,0],[0,1,0],[0,0,1]])` -- they all use the same np.array class, so it wouldn't make much sense for me for us to have different classes based on dimensionality/shape alone.

**Comment by clegaspi** [comment]
WIth #163 the complex value handling and np type coercion have been implemented. We will probably want to revisit the rejection of complex values by models later on when we have a use case/more bandwidth.

Will close this issue and open a new one for splitting up the quantity class.
