### ISSUE TITLE
[Priority] Add implementing author field to model metadata

### ISSUE THREAD

**Issue by mkhorton** [materialsintelligence/propnet#160]
Before we start losing track. Was hoping to automate this via git history but it's been necessary to change the model format a few times, so true authorship information is getting lost.

Suggest this is given a field name `implemented-by` and it's a list of Github usernames. Then we can hook into the Github api later to give links to authors etc on the web app.

**Comment by mkhorton** [comment]
You can check the git history for the model on GitHub. It should be fairly clear who created them vs who just reformatted.. Vahe and John have made a few, otherwise it’ll mostly be David, Joey and myself.

**Comment by mkhorton** [comment]
Maybe it is unclear because the files have been moved a bunch (which emphasises why we need to add this info sooner than later!)

You can also check the GitHub summary/insights page for this project and click on each author to see what commits they’ve made, perhaps that’s easier, because the other contributors have only made a few commits.

**Comment by clegaspi** [comment]
This is done.
