### ISSUE TITLE
dielectric-gap relations

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#2]
There are various dielectric constant (index of refraction) and band gap relations, see:

[1] N.M. Ravindra, P. Ganapathy, J. Choi, Energy gap-refractive index relations in semiconductors - An overview, Infrared Phys. Technol. 50 (2007) 21–29.

**Comment by mkhorton** [comment]
Added Ravindra model in #94, lots more in this paper still to add

**Comment by computron** [comment]
I implemented a bunch of these earlier in atomate builders:

```
                eps = m["dielectric"]["epsilon_static_avg"]  # electronic portion of eps ("eps_static") approximates eps_inf
                n = math.sqrt(eps)  # sqrt(eps_inf) to get refractive index
                d = {}
                d["gap_moss"] = (95 / n**4) if n > 0 else None
                d["gap_gupta-ravindra"] = (4.16-n)/0.85 if n <= 4.16 else None
                d["gap_reddy-anjaneyulu"] = 36.3/math.exp(n)
                d["gap_reddy-ahamed"] = 154/n**4+0.365 if n > 0 else None
                d["gap_herve_vandamme"] = 13.47/math.sqrt(n**2-1)-3.47 if n > 1 else None
```

I found the reddy-ajaneyulu one to be one of the better ones

**Comment by mkhorton** [comment]
Cool, thanks. Yeah I think Moss is only interesting for historical reasons, not so sure about the others.

**Comment by montoyjh** [comment]
All of these have been added.
