### ISSUE TITLE
Clarify vocabulary for material property vs. symbolic representation

### ISSUE THREAD

**Issue by clegaspi** [materialsintelligence/propnet#212]
I know that, historically, Symbols were called Properties, but that name was rejected because of name clashes with Python's `property` built-in. There remain pieces of code which use "property" to mean "symbol" and "symbol" to mean "equation variable", which makes for difficult reading of the code. For example, in `Model`, there is `map_property_to_symbol()` and `map_symbol_to_property()`. I would like to revisit this language to make sure it's clear what we are talking about.

PROPOSED VOCABULARY:
- **Definition**: a property of a material, such as band gap
    - **Possible representations**:
        - symbol
        - property (in code, abbreviate to "prop" or attach a prefix/suffix like "property_type")
        - attribute (in code, do not abbreviate to "attr" because it's close to `setattr` or `getattr` or `hasattr`)
        - trait
- **Definition**: symbolic representation of the value of a material's property (e.g. "E\_g") in an equation
    - **Possible representations**:
        - symbol
        - token
        - glyph
        - moniker

My thoughts on the above options:
- It is probably the easiest to use symbol/token because it is the least work and the association of the word "symbol" to the property of a material is easy enough to teach the user, as long as we're consistent between the YAML and class implementation. "glyph" also seems mathy.
- property/symbol has probably the most natural use of language. However, the use of "property" still feels like it could be cumbersome to make clear in code, such that we're not encroaching on the Python builtins. This goes for attribute/symbol as well, but to a somewhat lesser degree.
- trait/symbol is nice because the language feels a little more natural than symbol/token, but less than property/symbol, because trait and property are close synonyms, and symbol feels more like a mathematical term and mirrors the vocabulary of `sympy`.

**Comment by mkhorton** [comment]
I don't have much of an opinion on vocabulary as long as it's (a) consistent and (b) we have a glossary.rst file in the documentation or similar to keep track of everything. I think this is the most important thing.

I would say no to moniker and glyph and probably token ... Maybe prop is fine? Some Python codes use a trailing underscore to disambiguate from inbuilt names, that's also an option.

**Comment by clegaspi** [comment]
I had an epiphany last night and I've decided to go with symbol/variable.

**Comment by mkhorton** [comment]
Great! Let's have this be the last rename and move on 😅 have you added a glossary to the docs? can just be a bullet list or something at this point

**Comment by mkhorton** [comment]
Just to clarify, what’s happening to Quantity?

**Comment by clegaspi** [comment]
What do you mean? The Quantity module _should_ be consistent with this naming convention already.

**Comment by clegaspi** [comment]
Also, I have not added a glossary, but I'm not done with the PR yet.

**Comment by mkhorton** [comment]
I'm just checking I have the hierarchy consistent.

Maybe all this naming confusion is a sign of a bad design, in the sense that we could just have e.g. a band gap object, if it has a value then it has a value, and if it doesn't it just refers to the band gap in the abstract sense. You could even create a class dynamically, so you could have a `BandGap` class synthesized, then the type would refer to what it is in an abstract sense, and then it could have a value associated with it etc.

**Comment by clegaspi** [comment]
Clarified this offline. Merged in #220
