### ISSUE TITLE
Fork pint's unit definitions into propnet

### ISSUE THREAD

**Issue by mkhorton** [materialsintelligence/propnet#221]
We should really maintain our own independent unit definition file.

**Comment by clegaspi** [comment]
As opposed to just adding them programmatically like we do now.

**Comment by mkhorton** [comment]
To initialize the unit registry, pint references its `constants_en.txt` file, I'm just suggesting we make a copy of that file in our own repo and reference it.

This way we can add additional units to that file ourselves (for example, energy/atom) without having to clutter up the __init__.py which is where we currently do that, and it also means that we won't end up with inconsistent data if pint happens to change its unit definitions and we don't notice, e.g. updating a value for a fundamental constant.

**Comment by mkhorton** [comment]
Done
