### ISSUE TITLE
Notation for "units" in properties is difficult to understand

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#25]
I understand the desire to re-use pint notation, but maybe explain it and make it easy for people? e.g. give an example of what some complex unit looks like and what the various components are.

**Comment by mkhorton** [comment]
Good idea! Let's do this.

We could also instead have units as strings and just auto-parse them, that might be easier. There will be edge cases where it might be possible to define the wrong units, but hopefully that won't happen too often.
