### ISSUE TITLE
Suggest to rename PropertyMetadata to PropertyType

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#29]
PropertyMetadata could include things like the conditions the property was measured under or the type of technique used to measure the property

**Comment by computron** [comment]
the root docs seem to refer to it as PropertyType actually, just the code calls it PropertyMetadata

**Comment by mkhorton** [comment]
Agree this is a bad name, we have a lot of overloaded terms currently -- will be especially confusing to newcomers. This is being addressed.
