### ISSUE TITLE
symbol_out can usually be auto-detected?

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#32]
I think the base class has symbol_out be optional, but the actual models seem to require it

Perhaps you want the following:
i) symbol_out is required in the model.evaluate() AND
ii) the base model class implements a method that allows you to provide a symbol_input dictionary and gives you a list of potential symbol_outputs that the model can produce (None if nothing). Easy to get with connections dict?

**Comment by dmrdjenovich** [comment]
I plan on working on this tonight! Sorry for delays here.

**Comment by mkhorton** [comment]
`symbol_out` was removed
