### ISSUE TITLE
why G = symbols_and_values_in.get('G')

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#34]
You have:

G = symbols_and_values_in.get('G')

why not

G = symbols_and_values_in['G']

If 'G' does not exist in symbols and values, the latter will cause the code to fail at the actual point of failure (cannot load G). The former will cause the code to fail somewhere downstream, which will always be less clear as to what is happening. e.g., even in this simplest case, when the code fails it won't be clear that 'G' was the missing parameter

**Comment by mkhorton** [comment]
Good point, this should be changed..
