### ISSUE TITLE
Option to include a default value for the property/condition

### ISSUE THREAD

**Issue by vtshitoyan** [materialsintelligence/propnet#69]
The one thing that comes to mind now is the relative magnetic permeability, which is around 1 for most of the materials. I define refraction index n as a function of electrical permittivity and magnetic permeability, without a default value for \mu it won’t compute n and other optical properties that depend on n. However, in most cases, it makes sense to use 1 for \mu and propagate the graph.

We should, however, have a flag notifying the user that a default value was used and the result might not be precise.

Other things might later include e.g. a default wavelength for light, default sample thickness, etc.

**Comment by montoyjh** [comment]
As of #147, this can be done at the material level by invoking a material using:

```
m = Material(add_default_quantities=True)
```

or 

```
m = Material()
m.add_default_quantities()
```

Which will add default quantities if they're not present in the material, after which graph evaluation can be done.

Also added temperature of 300K and magnetic permeability of 1 as default quantities.
