### ISSUE TITLE
high k dielectric descriptors

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#73]
See paper

Petousis, I., Mrdjenovich, D., Ballouz, E., Liu, M., Winston, D., Chen, W., Graf, T., Schladt, T. D., Persson, K. A. & Prinz, F. B. High-throughput screening of inorganic compounds for the discovery of novel dielectric and optical materials. Sci. Data 4, 160134 (2017).

<img width="674" alt="screen shot 2018-04-01 at 12 02 49 pm" src="https://user-images.githubusercontent.com/986759/38176492-bd06fe4c-35a4-11e8-9ce6-a36562795547.png">

**Comment by dmrdjenovich** [comment]
Figures of Merit have been added.
