### ISSUE TITLE
minor spelling issues throughout propnet

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#78]
"vise versa"

"comlex permittivity"

**Comment by mkhorton** [comment]
just flagging that we also have issues with some non-standard Google docstrings too

**Comment by montoyjh** [comment]
I think the quality of the verbiage has increased considerably enough to close this issue.  I've also just done a quick walkthrough with the IDE (which spellchecks) and haven't noticed anything that's not intentional.
