### ISSUE TITLE
naming: Symbol and SymbolType

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#79]
I find the names "Symbol" and "SymbolType" to be very unintuitive. I would think of them more as PropertyType and Property. i.e., saying that "Young's modulus=200GPa" is a "symbol" of a material makes no sense to me. Calling it a "property" makes more sense and also fits in with the idea of "propnet". Also the add_property() method makes more sense if you feed in a Property object. etc. etc.

**Comment by mkhorton** [comment]
This was addressed, SymbolType was removed. They are now Quantity and Symbol respectively (of which Symbols can be either a property or condition or generic Python object, so in this terminology, "Young's modulus=200GPa" does indeed now have a property of "Young's modulus" and quantity associated with that property of "200GPa").

This might be developer further later, i.e. formally making a Property subclass
